services:
  postgres:
    image: postgres:15.1
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}_${NODE_ENV}
    restart: always

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}

  frontend:
    build: ../frontend
    restart: unless-stopped
    env_file: ../frontend/.env
    ports:
      - $FRONT_PORT:3000

volumes:
  db:
    driver: local